
volumes:
  grafana_vol: {}
  pg_data:
  
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=Info
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - lan
  grafana:
   
    image: grafana/grafana-enterprise
    volumes:
      - grafana_vol:/var/lib/grafana
    depends_on:
      - db
    container_name: grafana
    ports:
      - 3030:3000
    networks:
      - lan
    
  spring_application:
    depends_on:
      - db
    build: .
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Info
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=root

    networks:
      - lan
    ports:
      - 8080:8080


     
networks:
  lan:
    driver: bridge